
def search_users(query: str, dtsg: str = None, session_id: str = None):
  '''
  Searches user by the specified query.

  Args:
    query (str): text to look users for. Potentially usernames or complete names.
    dtsg (str): Value generated by Facebook to validated the session
    session_id (str): Cookie identifier for the user session

  Returns:
    List[User]: List of most relevant results matching the query
  '''
  pass


def search_posts(query: str, dtsg: str = None, session_id: str = None, limit: int = 10, delay: int = 5):
  '''
  Performs a search of posts matching the query or posted by users whose username
  matches the query

  Args:
    query (str): Search query.
    dtsg (str): Value generated by Facebook to validated the session
    session_id (str): Cookie identifier for the user session
    limit (int, optional): Maximum amount of posts to search for. Defaults to 10.
    delay (int, optional): Delay between requests in seconds. Defaults to 5.

  Returns:
    List[PostNode]: List of nodes containing the most relevant threads results matching the query.
  '''
  pass